name: "ecom-cms-test"

services:
  remix:
    #    image: app-dremix1-node:latest
    build:
      context: ./docker/node
      args:
        - UID=${UID}
        - GID=${GID}
        - USER_NAME=${USER_NAME}
    user: 1000:1000
    volumes:
      - ./source:/app
    ports:
      - 3000:3000
    command:
      - npm
      - run
      - dev
